### ISSUE TITLE
Regular Trim material still don't render on Silent Gear item

### ISSUE THREAD

**Issue by Dowar** [Andrew6rant/Dynamic-Trim#10]
The last update fixed the problem with a lot of armor but for Silent Gear mod the patch only fix the bug of the alloy becoming gray with vanilla trim material, the trim itself still don't render on item (other materials still work perfectly)

Tested with forge (47.2.1) in 1.20.1

**Comment by Bawnorton** [comment]
I'll take a look at what cursed things silent gear does to their armour items.

**Comment by Bawnorton** [comment]
This was a bug w/ AllTheTrims, has been patched in [AllTheTrims 3.3.3](https://github.com/Bawnorton/AllTheTrims/releases/tag/3.3.3)
