### ISSUE TITLE
Compatibility with Gloves from The Aether?

### ISSUE THREAD

**Issue by MysticcWaters** [Andrew6rant/Dynamic-Trim#11]
The Aether mod adds a new "armor" type in Gloves (it's technically a Curio, but is considered part of armor sets). These Gloves can also be trimmed. Would it be possible to get compatibility for them?

![Screenshot 2023-12-04 095243](https://github.com/Bawnorton/Dynamic-Trim/assets/130418925/3c9609ac-2f4e-45c2-915f-1a9c65f154a1)

**Comment by Bawnorton** [comment]
Maybe at some point in the future, it's not planned. Can always bring it to the aether team, it requires individual texture to be made for each template. Eg for chestplate https://github.com/Bawnorton/Dynamic-Trim/tree/stonecutter/src/main/resources/assets/minecraft/textures/trims/items/chestplate
