### ISSUE TITLE
z fighting on some items when holding

### ISSUE THREAD

**Issue by Pikldoornob** [Andrew6rant/Dynamic-Trim#13]
![image_2024-01-09_143726586](https://github.com/Bawnorton/Dynamic-Trim/assets/154773521/691c0821-7e68-496d-9e72-93b9162c5fed)

**Comment by Bawnorton** [comment]
https://bugs.mojang.com/browse/MC-259368

**Comment by peow** [comment]
this resourcepack aims to fix this problem, but just for vanilla, so it doesnt work with Dynamic Trim
https://modrinth.com/resourcepack/trims-fix
