### ISSUE TITLE
Compat with Trimmed

### ISSUE THREAD

**Issue by arzadu** [Andrew6rant/Dynamic-Trim#16]
Honestly not sure if this is possible, but compatibility with custom trims added with [Trimmed](https://github.com/dhyces/trimmed/wiki/Getting-Started---For-Everyone) would be absolutely magnificent. Even if it was only for new materials and not whole trims, it would be very cool! Currently, new trims make an armor piece into the texture not found magenta and black.

**Comment by Bawnorton** [comment]
There don't appear to be any mod that use Trimmed for trimming armour. All I can find is an old version of pigsteel that no longer uses it. Textures should now fall back to the vanilla trim texture if the dynamic trim cannot find an appropriate override texture.
