### ISSUE TITLE
[1.20.1]BUG conflict with Expanded Combat mod, causing texture issues (showing black and purple)

### ISSUE THREAD

**Issue by ColdTearsYY** [Andrew6rant/Dynamic-Trim#17]
Hello there and appreciate your work :) Could you please see this?
After binary search handy and I found that with Dynamic Trim installed, some textures in Expanded Combat mod didn't show properly.
version 1.4.1 mc1.20.1      Expanded Combat: https://www.curseforge.com/minecraft/mc-mods/expanded-combat
![20240311234408](https://github.com/Bawnorton/Dynamic-Trim/assets/65808439/b2cbb719-e749-432f-a4a8-4e896401e539)

**Comment by Bawnorton** [comment]
Forge and <1.20.1 no longer supported. If expanded combat updates to 1.21 and supports neoforge and this is still occurs, open a new issue in https://github.com/Bawnorton/RuntimeTrims
