### ISSUE TITLE
[Suggestion] Default armor texture when encountering an issue as the base armor texture instead of missing texture black/purple

### ISSUE THREAD

**Issue by Lucipo** [Andrew6rant/Dynamic-Trim#18]
Ive had some issues with this mod working with Trimmed mod, aswell as with custom trims from the Aether Redux Mod that results in a missing texture. Make this default to the base item texture like it does with modded items paired with vanilla trims that it doesnt recognize

![image](https://github.com/Bawnorton/Dynamic-Trim/assets/36358294/b1363a85-8972-4a3a-b5ec-5b28ac20f245)

**Comment by Lucipo** [comment]
Oh yeah this mod completely breaks CIT Resewn's Optifine CIT models on forge 1.20.1

**Comment by Bawnorton** [comment]
Latest update will fall back to vanilla texture and <1.20.1 + forge are no longer supported
