### ISSUE TITLE
State of Dynamic Trim

### ISSUE THREAD

**Issue by Bawnorton** [Andrew6rant/Dynamic-Trim#20]
Development is currently paused so I can focus on my studies.

I aim to have [AllTheTrims](https://github.com/Bawnorton/AllTheTrims) and DT re-written over the summer and unify the codebases to avoid large amounts of duplicate code and get rid of the huge amount of technical debt present in both. Both mods have very similar internals which will be pulled out into a separate library so that I don't spend half my time copying over the system every update. 

Expect a more stable, more performant version of the mod at some point during the summer.

**Comment by thevalleyy** [comment]
Hey, just wondering, are you still developing this mod?
totally fine if not, but knowing the state of development would be nice.
greetings from Germany

**Comment by Bawnorton** [comment]
It's next in my list of projects that need updating. No ETA, apologies it's taking a while, I have too many projects 😅

**Comment by Bawnorton** [comment]
Work on 1.21 port has started

**Comment by Bawnorton** [comment]
Finished

**Comment by Fyoncle** [comment]
> Finished

No backport for 1.20.1? :c

**Comment by Bawnorton** [comment]
No

**Comment by Fyoncle** [comment]
> No

So cruel :(
