### ISSUE TITLE
[Bug] Z-Fighting on hand held models

### ISSUE THREAD

**Issue by Fyoncle** [Andrew6rant/Dynamic-Trim#23]
![image](https://github.com/user-attachments/assets/b41f577a-bb42-48fa-aba2-20b1041fcaab)
![image](https://github.com/user-attachments/assets/4190cde2-a5b1-421b-87a3-116adadfdee1)

1.20.1 Fabric
Dynamic Trim 1.4.1

**Comment by Bawnorton** [comment]
https://bugs.mojang.com/browse/MC-259368

**Comment by Fyoncle** [comment]
> https://bugs.mojang.com/browse/MC-259368

Uh? how i meant to get this fixed then :D

**Comment by Bawnorton** [comment]
wait for mojang to fix it
