### ISSUE TITLE
Doesn’t work with MC-Creator armour

### ISSUE THREAD

**Issue by Rebel459** [Andrew6rant/Dynamic-Trim#6]
See title. I’m not sure if this is intentional or not, but it would be great if it would work on modded armour too.

**Comment by Bawnorton** [comment]
Which armour specifically, this works with modded armour that is implemented in a not jank way

**Comment by Rebel459** [comment]
That’s weird… the mods armor I tested were made using mcreator… but that armor had no issues with all the trims or any other mod.

With Dynamic Trims, no trim texture renders on the item at all

Is there any way I can fix this on my end, maybe?

**Comment by Bawnorton** [comment]
>not jank way
>mc creator

Yeah I have no idea, mc creator makes some absolutely cursed (on the inside) mods with very jank code. I don't think this is easily fixable 

Can you send a link to the mod?

**Comment by Rebel459** [comment]
Sure! I reckon it probably affected all 3 mods tbh, 
https://modrinth.com/mod/endgame-reborn
https://modrinth.com/mod/progression-reborn
https://modrinth.com/mod/legacies-and-legends

My theory is it affects all mcreator mods, but my source code hasn’t been publicly updated in a while due to laziness.

I do know Purejosh uses mcreator, so maybe look at https://modrinth.com/mod/pure-copper-tools for source?

**Comment by Bawnorton** [comment]
Can you also send your log file for when you load the broken armour mod and dynamic trims

**Comment by Rebel459** [comment]
Sure, I can do that.

**Comment by Rebel459** [comment]
[latest.log](https://github.com/Andrew6rant/Dynamic-Trim/files/12482027/latest.log)

**Comment by Bawnorton** [comment]
yeah nothing useful unfortunately

**Comment by Rebel459** [comment]
maybe its way of checking if the armor is armor equipment doesn't work with mcreator / they don't register it in that spot?

**Comment by Rebel459** [comment]
how does Dynamic Trims know the difference between armor and non-armor textures?

**Comment by Rebel459** [comment]
https://github.com/Andrew6rant/Dynamic-Trim/pull/5 this could be an eventual fix, but maybe there's a way to edit the mcreator code to register it as whatever dynamic trims is looking for?

**Comment by Bawnorton** [comment]
#5 improves the code quality and compatibility with other mods trying to do the exact same thing, doesn't change the functionality. The mod uses the model files and intercepts them when they're loaded in, the mc-creator mods you sent me appear to have their model files setup correctly such that it would work. Can you test explicitly with https://modrinth.com/mod/pure-copper-tools as the other mods are closed source so I can't see what they are doing without decompiling.

**Comment by Rebel459** [comment]
my mods are registered the exact same way as pure copper due to them both using mcreator generation, so it's strange that none of them are working

**Comment by Rebel459** [comment]
also, I've tested Pure Emerald Tools, and nope, nothing works

**Comment by Bawnorton** [comment]
¯\\\_(ツ)\_/¯  I'll give it a look tmrw. MC Creator moment

**Comment by Rebel459** [comment]
yeah lol, will test on a vanilla client too, just in case

**Comment by Rebel459** [comment]
can confirm it affects vanilla, so not a modpack issue

**Comment by Rebel459** [comment]
It just works for me now, idk why, but not complaining.
