### ISSUE TITLE
1.20.2 Compatibility?

### ISSUE THREAD

**Issue by Jackuhlf** [Andrew6rant/Dynamic-Trim#7]
title explains

**Comment by Bawnorton** [comment]
Waiting for Architectury to support NeoForge 1.20.2 to officially support it, the latest version should work on 1.20.2 fabric but it might not work on 1.20.2 forge because of the split. Try it and see.

**Comment by Bawnorton** [comment]
Will be jumping to the last 1.20.x version that is released (likely 1.20.5) as there is very little demand for the intermediary versions and maintaining every version across all my mods is not feasible for me.
