### ISSUE TITLE
Vanilla Ingot Trim Materials Don't Show with AllTheTrims

### ISSUE THREAD

**Issue by Partonetrain** [Andrew6rant/Dynamic-Trim#8]
using dynamictrim-1.2.1-fabric+1.20.1 and allthetrims-3.2.5-fabric+1.20.1
Examples:
![image](https://github.com/Andrew6rant/Dynamic-Trim/assets/19861808/8e762d1c-4e16-49f0-ace8-d63e2ad2481f)
![image](https://github.com/Andrew6rant/Dynamic-Trim/assets/19861808/af4c1119-8355-44bc-8bbf-ef45cd4c6c6d)

**Comment by Bawnorton** [comment]
Confirmed, related to [AllTheTrims#17](https://github.com/Bawnorton/AllTheTrims/issues/17)

**Comment by Bawnorton** [comment]
Fixed in 1.3.0
