### ISSUE TITLE
compatibility with Elytra Trims mod 

### ISSUE THREAD

**Issue by peow** [Andrew6rant/Dynamic-Trim#9]
hello, can u add compatibility with Elytra Trims mod by "kikugie"?
![image](https://github.com/Andrew6rant/Dynamic-Trim/assets/105888751/73abcd3d-fccc-48db-812d-652c93772a0e)
this mod add trims to elytra, but the trims dont render inside the inventory
![image](https://github.com/Andrew6rant/Dynamic-Trim/assets/105888751/d376a6bf-6075-465c-9fa9-16e63b22e062)

**Comment by peow** [comment]
an update: Elytra Trims already render trims inside the inventory, but its not dynamic, is always the same pattern
![image](https://github.com/Bawnorton/Dynamic-Trim/assets/105888751/6085fa13-b315-4ec4-bb64-3d626478f79b)

**Comment by Bawnorton** [comment]
Dynamic elytra textures may be included in future but it's not planned anytime soon
